### ISSUE TITLE
`os_sorted` fails to sort current directory

### ISSUE THREAD

**Issue by xymy** [SethMMorton/natsort#142]
**Describe the bug**
`ValueError` is raised when sorting current directory `'.'` or `'./'` or `'.\\'`.

**Expected behavior**
The current directory should be sorted correctly without error.

**Environment (please complete the following information):**
 - Python Version: 3.9
 - OS: both Windows and Ubuntu
 - If the bug involves `LOCALE` or `humansorted`:
    - Is `PyICU` installed? No
    - Do you have a locale set? If so, to what? No

**To Reproduce**

```python
Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from natsort import os_sorted
>>> os_sorted(['.'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Software\Python39\lib\site-packages\natsort\natsort.py", line 929, in os_sorted
    return sorted(seq, key=os_sort_keygen(key), reverse=reverse)
  File "D:\Software\Python39\lib\site-packages\natsort\natsort.py", line 786, in <lambda>
    OSSortKeyType, lambda x: tuple(map(_winsort_key, _split_apply(x, key)))
  File "D:\Software\Python39\lib\site-packages\natsort\natsort.py", line 770, in _split_apply
    return utils.path_splitter(str(v))
  File "D:\Software\Python39\lib\site-packages\natsort\utils.py", line 890, in path_splitter
    *path_parts, base = s.parts
ValueError: not enough values to unpack (expected at least 1, got 0)
```

**Comment by SethMMorton** [comment]
This is originating from behavior from `pathlib` that I would call surprising

```python
In [6]: import pathlib

In [7]: pathlib.Path("a").parts
Out[7]: ('a',)

In [8]: pathlib.Path("a.").parts
Out[8]: ('a.',)

In [9]: pathlib.Path(".a").parts
Out[9]: ('.a',)

In [10]: pathlib.Path(".").parts
Out[10]: ()

In [11]: pathlib.Path("./").parts
Out[11]: ()

In [12]: pathlib.Path("././").parts
Out[12]: ()

In [13]: pathlib.Path("..").parts
Out[13]: ('..',)

```

I would not have expected `pathlib.Path(".").parts` to return an empty tuple, and this is the root of the problem.
