### ISSUE TITLE
Error while sorting dates if `NaT`

### ISSUE THREAD

**Issue by Enissay** [SethMMorton/natsort#170]
**Describe the bug**
Throws error when dates contain `NaT`.
`natsort` seems to replace the missing values by -inf, which doesn't compare to timestamps.
```python
TypeError: 'values' is not ordered, please explicitly specify the categories order by passing in a categories argument.
```

**Expected behavior**
If empty values, then replace with a value that can compare unlike above.

**Environment (please complete the following information):**
 - Python Version: 3.10
 - OS Windows

**To Reproduce**
```python
import pandas as pd
import numpy as np
from natsort import natsort_key

df = pd.DataFrame({
    "ip": ['10.10.11.30', '10.10.11.30', '10.10.11.30', '10.2.2.10', '10.10.2.1', '10.2.2.2'],
    "path": ['/data/foo/err', '/data/foo/zone', '/data/foo/err', '/data/foo/zone', '/data/foo/zone', '/data/foo/tmp'],
    "date": ['25/01/2024', '25/01/2024', '01/08/2020', '23/01/2024', '', '25/01/2024'],
    "count": [3, 10, 20, 5, 20, 50]
})

df['date'] = pd.to_datetime(df['date'], dayfirst=True)

df_sorted = df.sort_values(by=['ip', 'date', 'count'], key=natsort_key)
print(df_sorted.to_markdown)
```
<details><summary>Errors</summary>
<pre><code>import pandas as pd
Traceback (most recent call last):
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 1516, in safe_sort
    sorter = values.argsort()
             ^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'Timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 1516, in safe_sort
    sorter = values.argsort()
             ^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'Timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\sandbox\.venv\Lib\site-packages\numpy\core\fromnumeric.py", line 59, in _wrapfunc
    return bound(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'Timestamp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\arrays\categorical.py", line 460, in __init__
    codes, categories = factorize(values, sort=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 802, in factorize
    uniques, codes = safe_sort(
                     ^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 1528, in safe_sort
    ordered = _sort_mixed(values)
              ^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 1588, in _sort_mixed
    num_argsort = np.argsort(values[num_pos])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\numpy\core\fromnumeric.py", line 1133, in argsort
    return _wrapfunc(a, 'argsort', axis=axis, kind=kind, order=order)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\numpy\core\fromnumeric.py", line 68, in _wrapfunc
    return _wrapit(obj, method, *args, **kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\numpy\core\fromnumeric.py", line 45, in _wrapit
    result = getattr(asarray(obj), method)(*args, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'float' and 'Timestamp'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\arrays\categorical.py", line 460, in __init__
    codes, categories = factorize(values, sort=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 802, in factorize
    uniques, codes = safe_sort(
                     ^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 1526, in safe_sort
    ordered = _sort_tuples(values)  # type: ignore[arg-type]
              ^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\algorithms.py", line 1608, in _sort_tuples
    indexer = lexsort_indexer(arrays, orders=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\sorting.py", line 351, in lexsort_indexer
    cat = Categorical(k, ordered=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\arrays\categorical.py", line 466, in __init__
    raise TypeError(
TypeError: 'values' is not ordered, please explicitly specify the categories order by passing in a categories argument.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\dev\sandbox\tests\sandbox.py", line 16, in <module>
    df_sorted = df.sort_values(by=['ip', 'date', 'count'], key=natsort_key)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\frame.py", line 7167, in sort_values
    indexer = lexsort_indexer(
              ^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\sorting.py", line 351, in lexsort_indexer
    cat = Categorical(k, ordered=True)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\dev\sandbox\.venv\Lib\site-packages\pandas\core\arrays\categorical.py", line 466, in __init__
    raise TypeError(
TypeError: 'values' is not ordered, please explicitly specify the categories order by passing in a categories argument.

Process finished with exit code 1
</code></pre>
</details>

**Comment by SethMMorton** [comment]
A couple thoughts

- In general, `natsort` is only guaranteed to operate successfully on built-in types.
  - The general guidance is to use a key to transform your non-builtin type to some sort of sortable representation based on built-in types via a `key` function.
- Given that the timestamp series already has a well-defined sort order, I would argue that running `natsort` on it is not needed.

I think you could probably fix this by simply not running `natsort` on that column. Maybe something like (untested):

```py
df_sorted = df.sort_values(by=['ip', 'date', 'count'], key=lambda i, d, c: (natsort_key(i), d, natsort_key(c)))
```

**Comment by Enissay** [comment]
Aha, that's the workaround I have used indeed.
I thought it was a bug! But if that is how it is meant to work, than all good :-)
Thank you for the explanation

**Comment by SethMMorton** [comment]
Yeah, it's not really a bug, but it's certainly not a feature either. If you are familiar with C, it's more like _undefined behavior_ - `natsort` neither explicitly forbids nor allows sorting non-builtin types. For some non-builtin types it may fortuitously work, and for others it may blow up in your face. To stay on the safe side one should stick with the defined behavior.
